---
- name: Add SBT repo
  apt_repository: repo='deb https://dl.bintray.com/sbt/debian /' state=present
- name: Add SBT repo key
  apt_key: keyserver='hkp://keyserver.ubuntu.com:80' id='642AC823'
- name: Install SBT
  apt: name=sbt state=present update_cache=yes
